## Simple Makefile

CC=gcc

CFLAGS= -Wall -Wextra -Werror -Wunused
LDFLAGS=
NAME=TEST
LDLIBS= 

SRC= $(NAME).c main.c

all: 
	$(CC) $(CFLAGS) $(SRC) -o $(NAME)

main: 

clean:
	rm -f *~ *.o
	rm -f main

#END